#!/usr/bin/env python

from xtore.cli.StorageTestCLI import run
if __name__ == '__main__': run()

class Ring extend Ring_root:
	parent Ring_root | Ring | Null
		
class Ring_root:
	int ring_layer
	int ring_prime
	int position(key)
		
class StorageUnit:
	str data 
	int position
	Ring ring
		
class PrimeRings:
	Ring_root root 